apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tenant-portal-storage
  namespace: default
spec:
  storageClassName: topolvm-provisioner
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
